/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalhanaval2;

import java.util.HashSet;

/**
 *
 * @author Cadore
 */
public class TelaBatalha extends javax.swing.JFrame {

    private final BatalhaNaval2 jogo;

    /**
     * Creates new form TelaBatalha
     */
    public TelaBatalha(BatalhaNaval2 jogo) {
        this.jogo = jogo; // Inicialize a referência de BatalhaNaval2
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Start = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        seletorNavio = new javax.swing.JComboBox<>();
        campoLinha = new javax.swing.JTextField();
        campoColuna = new javax.swing.JTextField();
        BotaoAcao = new javax.swing.JButton();
        vertical = new javax.swing.JToggleButton();
        avisos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Start.setText("Começar");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        seletorNavio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Navio Pequeno", "Navio Medio", "Navio Grande" }));
        seletorNavio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorNavioActionPerformed(evt);
            }
        });

        campoLinha.setText("Linha");
        campoLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLinhaActionPerformed(evt);
            }
        });

        campoColuna.setText("Coluna");
        campoColuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoColunaActionPerformed(evt);
            }
        });

        BotaoAcao.setText("colocar");
        BotaoAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAcaoActionPerformed(evt);
            }
        });

        vertical.setText("Vertical");
        vertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verticalActionPerformed(evt);
            }
        });

        avisos.setText("avisos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vertical, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoAcao))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(seletorNavio, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(campoLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoColuna, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avisos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(seletorNavio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoColuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoAcao)
                            .addComponent(vertical)))
                    .addComponent(avisos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(Start)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Start))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLinhaActionPerformed

    private void campoColunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoColunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoColunaActionPerformed

    private void BotaoAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAcaoActionPerformed
        int linha = Integer.parseInt(campoLinha.getText());
        int coluna = Integer.parseInt(campoColuna.getText());

        if (jogo.isFasePlanejamento()) {
            if (jogo.pecas > 0) {
                if (jogo.posicaoValida(linha, coluna, jogo.tamanho)) {
                    jogo.posicionarNavio(linha, coluna, jogo.tamanho, jogo.vertical);
                } else {
                    System.out.println("posição ja ocupada");
                }
            } else{
            System.out.println("sem peças disponiveis aperte 'start");
        }

        }
       
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                System.out.print(jogo.tabuleiroPlayer[i][j] + " ");
            }
            System.out.println(" ");
        }
    }//GEN-LAST:event_BotaoAcaoActionPerformed

    private void seletorNavioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorNavioActionPerformed
        Object selectedItem = seletorNavio.getSelectedItem();
        String tipoSelecionado = selectedItem.toString();
        if (tipoSelecionado == "Navio Pequeno") {
            jogo.tamanho = 1;
        }
        if (tipoSelecionado == "Navio Medio") {
            jogo.tamanho = 2;
        }
        if (tipoSelecionado == "Navio Grande") {
            jogo.tamanho = 3;
        }
        System.out.println(jogo.tamanho);
    }//GEN-LAST:event_seletorNavioActionPerformed

    private void verticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verticalActionPerformed
        jogo.setVertical(!jogo.vertical);
        
    }//GEN-LAST:event_verticalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        BatalhaNaval2 jogo = new BatalhaNaval2();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBatalha(jogo).setVisible(true); // Passa a referência 'jogo' para TelaBatalha
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAcao;
    private javax.swing.JButton Start;
    private javax.swing.JTextField avisos;
    private javax.swing.JTextField campoColuna;
    private javax.swing.JTextField campoLinha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> seletorNavio;
    private javax.swing.JToggleButton vertical;
    // End of variables declaration//GEN-END:variables

    private boolean posicaoValida(int linha, int coluna, int tamanho) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
