/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package batalhanaval2;

import java.util.HashSet;
import javax.swing.JLabel;

/**
 *
 * @author Cadore
 */
public class TelaBatalha extends javax.swing.JFrame {

    private final BatalhaNaval2 jogo;

    /**
     * Creates new form TelaBatalha
     */
    public TelaBatalha(BatalhaNaval2 jogo) {
        this.jogo = jogo; // Inicialize a referência de BatalhaNaval2
        initComponents();
        Start.setVisible(false);
        mostraTabuleiroP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        seletorNavio = new javax.swing.JComboBox<>();
        campoLinha = new javax.swing.JTextField();
        campoColuna = new javax.swing.JTextField();
        BotaoAcao = new javax.swing.JButton();
        vertical = new javax.swing.JToggleButton();
        avisos = new javax.swing.JTextField();
        Start = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        seletorNavio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Navio Pequeno", "Navio Medio", "Navio Grande" }));
        seletorNavio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorNavioActionPerformed(evt);
            }
        });

        campoLinha.setText("Linha");
        campoLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLinhaActionPerformed(evt);
            }
        });

        campoColuna.setText("Coluna");
        campoColuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoColunaActionPerformed(evt);
            }
        });

        BotaoAcao.setText("colocar");
        BotaoAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAcaoActionPerformed(evt);
            }
        });

        vertical.setText("Horizontal");
        vertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verticalActionPerformed(evt);
            }
        });

        avisos.setText("avisos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vertical)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoAcao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seletorNavio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoLinha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoColuna, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avisos, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(seletorNavio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotaoAcao)
                            .addComponent(vertical)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(avisos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoColuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoLinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Start.setText("Começar");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(5, 5, 5, 5));

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);

        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2);

        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);

        jLabel4.setText("jLabel3");
        jPanel2.add(jLabel4);

        jLabel5.setText("jLabel3");
        jPanel2.add(jLabel5);

        jLabel6.setText("jLabel3");
        jPanel2.add(jLabel6);

        jLabel7.setText("jLabel3");
        jPanel2.add(jLabel7);

        jLabel8.setText("jLabel3");
        jPanel2.add(jLabel8);

        jLabel9.setText("jLabel3");
        jPanel2.add(jLabel9);

        jLabel10.setText("jLabel3");
        jPanel2.add(jLabel10);

        jLabel11.setText("jLabel3");
        jPanel2.add(jLabel11);

        jLabel12.setText("jLabel3");
        jPanel2.add(jLabel12);

        jLabel13.setText("jLabel3");
        jPanel2.add(jLabel13);

        jLabel14.setText("jLabel3");
        jPanel2.add(jLabel14);

        jLabel15.setText("jLabel3");
        jPanel2.add(jLabel15);

        jLabel16.setText("jLabel3");
        jPanel2.add(jLabel16);

        jLabel17.setText("jLabel3");
        jPanel2.add(jLabel17);

        jLabel18.setText("jLabel3");
        jPanel2.add(jLabel18);

        jLabel19.setText("jLabel3");
        jPanel2.add(jLabel19);

        jLabel20.setText("jLabel3");
        jPanel2.add(jLabel20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Start)
                        .addGap(194, 194, 194))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Start))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void mostraTabuleiroP() {
    // Cria uma matriz de JLabels com referências a cada JLabel (assumindo que jLabel1 até jLabel20 existem)
    JLabel[] labels = {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5,
                       jLabel6, jLabel7, jLabel8, jLabel9, jLabel10,
                       jLabel11, jLabel12, jLabel13, jLabel14, jLabel15,
                       jLabel16, jLabel17, jLabel18, jLabel19, jLabel20};

    // Itera pela matriz tabuleiroPlayer e atualiza os JLabels correspondentes
    int labelIndex = 0;
    for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 5; j++) {
            // Verifica se ainda temos labels para atualizar
            if (labelIndex < labels.length) {
                labels[labelIndex].setText(jogo.tabuleiroPlayer[i][j]);
                labelIndex++;
            }
        }
    }
}

    private void campoLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLinhaActionPerformed

    private void campoColunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoColunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoColunaActionPerformed

    private void BotaoAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAcaoActionPerformed
        int linha = Integer.parseInt(campoLinha.getText());
        int coluna = Integer.parseInt(campoColuna.getText());
        avisos.setText(" ");
        if (jogo.isFasePlanejamento()) {
            if (jogo.pecas > 0) {
                if (jogo.posicaoValida(linha, coluna, jogo.tamanho)) {
                    jogo.posicionarNavio(linha, coluna, jogo.tamanho, jogo.vertical);
                    mostraTabuleiroP();
                } else {
                    avisos.setText("posição ja ocupada");
                }
            } else {
                avisos.setText("sem peças disponiveis aperte 'start' ");
                Start.setVisible(true);

            }
        } else {

        }

        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                System.out.print(jogo.tabuleiroPlayer[i][j] + " ");
            }
            System.out.println(" ");
        }
    }//GEN-LAST:event_BotaoAcaoActionPerformed

    private void seletorNavioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorNavioActionPerformed
        Object selectedItem = seletorNavio.getSelectedItem();
        String tipoSelecionado = selectedItem.toString();
        if (tipoSelecionado == "Navio Pequeno") {
            jogo.tamanho = 1;
        }
        if (tipoSelecionado == "Navio Medio") {
            jogo.tamanho = 2;
        }
        if (tipoSelecionado == "Navio Grande") {
            jogo.tamanho = 3;
        }
        System.out.println(jogo.tamanho);
    }//GEN-LAST:event_seletorNavioActionPerformed

    private void verticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verticalActionPerformed
        jogo.setVertical(!jogo.vertical);
        if (jogo.vertical) {
            vertical.setText("Vertical");
        } else {
            vertical.setText("Horizontal");
        }

    }//GEN-LAST:event_verticalActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        jogo.setFasePlanejamento(false);
        BotaoAcao.setText("atirar");
        Start.setVisible(false);
    }//GEN-LAST:event_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        BatalhaNaval2 jogo = new BatalhaNaval2();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new TelaBatalha(jogo).setVisible(true); // Passa a referência 'jogo' para TelaBatalha

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAcao;
    private javax.swing.JButton Start;
    private javax.swing.JTextField avisos;
    private javax.swing.JTextField campoColuna;
    private javax.swing.JTextField campoLinha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> seletorNavio;
    private javax.swing.JToggleButton vertical;
    // End of variables declaration//GEN-END:variables

    private boolean posicaoValida(int linha, int coluna, int tamanho) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
